version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: postgre_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend/
    volumes:
      - static:/backend_static
      - media:/backend_media
    depends_on:
      - db
    env_file: .env

  frontend:
    container_name: frontend
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./infra/
    env_file: .env
    ports:
      - 9001:80
    volumes:
      - static:/static
      - media:/backend_media