# Generated by Django 3.2.3 on 2023-06-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
